import type { Metadata } from "next";
// import { GeistSans } from "next/font/google";
import "./globals.css";
import { Navbar } from "./Navbar/page";
import { Footer } from "./Footer/page";
import localFont from 'next/font/local';

const SFProDisplay = localFont({
  src: [
    {
      path: '../assets/fonts/SF-Pro-Display-Medium.ttf',
      weight: '500',
      style: 'normal',
    },
    {
      path: '../assets/fonts/SF-Pro-Display-Bold.ttf',
      weight: '700',
      style: 'normal',
    },
    {
      path: '../assets/fonts/SF-Pro-Display-Regular.ttf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../assets/fonts/SF-Pro-Display-Semibold.ttf',
      weight: '600',
      style: 'normal',
    },
  ],
  variable: '--font-sf-pro-display',
  display: 'swap',
});

// const geistMono = GeistSans({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${SFProDisplay.variable}`}>
      <body
        className={`antialiased flex flex-col min-h-screen font-sans`}
      >
        <Navbar />
        <main className="flex-grow">
          {children}
        </main>
        <Footer/>
      </body>
    </html>
  );
}