import type { Metadata } from "next";
import { Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navbar } from "./Navbar/page";
import { Footer} from "./Footer/page";


const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {
  return (
    <html lang="en">
      <body
        className={` ${geistMono.variable} antialiased flex flex-col min-h-screen`}
      >
        <Navbar />
        {/** Main content */}
        <main className="flex-grow">
        {children}
        </main>

        <Footer/>
      </body>
    </html>
  );
}
